image: gitpod/workspace-dotnet:latest

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      : dotnet build

github:
  prebuilds:
    master: true

vscode:
  extensions:
    - muhammad-sammy.csharp
